print("Programa para a conversão de dias, horas e minutos em segundos, visado para ser utilizado em exercícios de Física")
print()
D = int(input("Digite o número de dias: "))
print()
H = int(input("Digite o número de horas: "))
print()
M = int(input("Digite o número de minutos: "))
print()
S = int(input("Digite o valor de segundos: "))
print("O resultado é :", D*86400+H*3600+M*60+S)
input()
